### ISSUE TITLE
Launch parameters question?

### ISSUE THREAD

**Issue by LuxLuma** [SirPlease/Server4Dead-Project#3]
Hello,

> If you're going to adjust your Tickrate above 100, you will run into Boomer Vomit Range issues.
> You will need to add "-frametime 0.037 -frametime_override 0.037" to the launch parameters to resolve this, make sure to place them after the tickrate

What does "-frametime 0.037 -frametime_override 0.037" do?
These parameters there is little infomation about them.

Thanks.

**Comment by SirPlease** [comment]
If you want me to be a 100% honest, I don't know.
The sourcefile for this version of tickrate enabler has never been released and I no longer communicate with its developer.

All I know is that it's a setting that'll make the Boomer range be considerably more "normal".

**Comment by LuxLuma** [comment]
I can't really find any references of "-frametime_override" param, however I do find "-frametime" in a if for the boomer vomit in IDA, i'm not very experienced in IDA but "-frametime_override" looks useless to me.

Thanks anyways.
