### ISSUE TITLE
Sourcemod Anticheat is broken

### ISSUE THREAD

**Issue by CanadianJeff** [SirPlease/Server4Dead-Project#4]
I have been using this version of SMAC for almost 7 months and now it can be bypassed please update it or take it down as it is pointless now

**Comment by SirPlease** [comment]
Every Anti-Cheat can be bypassed, it doesn't mean they're pointless.
I didn't develop SMAC nor did I contribute to any of it, it's very outdated (2012) and it's open source which allows Anti-Cheat developers to test on it extensively to be able to bypass it.

Regardless, there's still plenty of people that get detected by SMAC and they're swifly banned (if you pay attention to your logs).

Feel free to re-open the issue once you've realized your mistake.

**Comment by CanadianJeff** [comment]
I have not made any mistake lots of people from the SIRPLEASE and EFREAK community join my server and I see USER moved to spectator for using THIRDPERSONSHOULDER

**Comment by CanadianJeff** [comment]
your so called community is toxic and trash I have about 10,100 hours on left 4 dead 2 and people with only 4,000 feel the need to use aimware aimbot and scripts in public matches

**Comment by SirPlease** [comment]
Alright, I just replied to your issue, but it seems you have other issues that are better suitable for real life treatment.
I wish you best.

**Comment by xWa11y** [comment]
> I have been using this version of SMAC for almost 7 months and now it can be bypassed please update it or take it down as it is pointless now

You do realise Sir is not the developer of SMAC right (Also, if there's a newer version you can... yknow, download it yourself?) Also, I more than highly doubt any anti-cheat created with sourcemod plugins (and is open source) will not be easily bypassable by cheaters, considering VAC itself can be bypassed.

> I have not made any mistake lots of people from the SIRPLEASE and EFREAK community join my server and I see USER moved to spectator for using THIRDPERSONSHOULDER

That's a client side command, that can only be used on campaign or servers that enable it, not a cheat.

> your so called community is toxic and trash I have about 10,100 hours on left 4 dead 2 and people with only 4,000 feel the need to use aimware aimbot and scripts in public matches

weird flex but ok.

Please stop making yourself look more stupid than you already have.

**Comment by CanadianJeff** [comment]
there is no newer version if there was it would be linked on here

I have many evidence and reason to believe that valve and the "pro" community profit from cheaters

**Comment by SirPlease** [comment]
The issue is closed and you have your information, there's no need to get all dramatic here.
Please don't use this github to out your frustrations about unrelated topics.

If you have any actual issues related to this github, feel free to open another issue.

**Comment by CanadianJeff** [comment]
if you need to have a community of cheaters I think it would be you that needs real life treatment

**Comment by 404UNFca** [comment]
> 
> 
> if you need to have a community of cheaters I think it would be you that needs real life treatment

Nobody cares about your community here. A lot of us run communities too. Doesn't make you special. Regardless, this isn't the place for this discussion. If you want this fixed, you have some options:

1. Hire a programmer to update it for you, but you'll have to provide them with info on what can be bypassed, what you want to add, etc.
2. Learn SourcePawn and do it yourself. There's a reason it's called "DIY".

Whichever option you choose, I'd like to also tack on a requirement to that; shut up.
